import Head from "next/head";
import { useState, useEffect } from "react";
import { Footer, Header } from "../elements";

export const Layout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>{children}</main>
      <Footer/>
    </>
  );
};
